# Generated by Django 4.2.1 on 2023-06-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_budget_last_week_spent_alter_budget_expenses_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Incomes'},
        ),
        migrations.AlterField(
            model_name='budget',
            name='last_week_spent',
            field=models.FloatField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='weekly_limit',
            field=models.FloatField(blank=True, max_length=9, null=True),
        ),
    ]
